import cohere
import numpy as np

co = cohere.Client("KxcXAqpat6ZZcsJbuVniMMByng0JaBPrpIXy6Pwr")

input = "IRON FER ZINC ZINC (ODINE (ODE BIOTIN BIOTINE COPPER CUIVRE MANGANESE MANGANESE INGREDIENTS / INGREDIENTS ; RICE, WHOLE GRAIN WHEAT, SUGAR/GLUCOSE-FRUCTOSE, SOY PROTEIN, WHOLE GRAIN OATS, SOY,PROTEIN CONCENTRATE, VEGETABLE OIL, BROWN SUGAR, SYRUP, RICE FLOUR, SALT, VEGETABLE Oil SHORTENING,HONEY, BARLEY MALT SYRUP, MOLASSES, COLOUR,CINNAMON, ARTIFICIAL FLAVOUR, SOY LECITHIN, BHT,CITRIC ACID,VITAMINS AND MINERALS: SODIUM L-ASCORBATE,{ALPHA TOCOPHEROL, NIACINAMIDE, ASCORBIC ACID, ZINC OXIDE, BIOTIN, ¢-CALCIUM PANTOTHENATE, IRON, COPPER OXIDE, PYRIDOXINE HYDROCHLORIDE, VITAMIN,ALMITATE, THIAMINE HYDROCHLORIDE, RIBOFLAVIN, ACID, POTASSIUM IODIDE, CHOLECALCIFEROI."
prompt = input + "isolate after ingredients"

response = co.generate(  
    model='command-xlarge-nightly',  
    prompt = prompt,  
    max_tokens=200,  
    temperature=0.750)

intro_paragraph = response.generations[0].text
print("RESPONSE", intro_paragraph)
